#!/bin/sh
# This file exists to document the proper way to initialize autotools,
# and so that those used to the presence of bootstrap.sh or autogen.sh
# will have an eaiser time.
autoreconf -i -v -f

# GNU Coding Standards say this:
#                                        [...] running the command
#     `make maintainer-clean' should not delete `configure' even if
#     `configure' can be remade using a rule in the Makefile.  More
#     generally, `make maintainer-clean' should not delete anything that
#     needs to exist in order to run `configure' and then begin to build
#     the program.  This is the only exception; `maintainer-clean' should
#     delete everything else that can be rebuilt.
echo "Clean files by 'make distclean', 'make maintainer-clean' (GNU defaults)."
echo "To remove all autogenerated files use 'make total-clean' (maintainer only)."
